#!/bin/bash

set -e
cd "$(dirname $0)/.."

rev="HEAD"
rev_date="$(git show -s --format=%cd --date=format:"%Y-%m-%d" $rev)"
rev_sha="$(git rev-parse --short $rev)"
output_file="Zips/swift-algorithms-on-sequences-$rev_date-$rev_sha.zip"

mkdir -p Zips

echo "==> Generating $output_file"
git archive -o "$output_file" "$rev"
